In [1]:
!nvidia-smi

Sat Jan 31 15:58:39 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.80                 Driver Version: 581.80         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060      WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   41C    P8              7W /   78W |     705MiB /   6144MiB |     11%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:

print(f"torch: {torch.__version__}")
print(f"numpy: {np.__version__}")
print(f"pandas: {pd.__version__}")

torch: 2.7.1+cu118
numpy: 2.3.5
pandas: 3.0.0


## Introduction to tensros

### Creating tensors

### Scalar

In [4]:
# scalar

scalar = torch.tensor(10)
scalar

tensor(10)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

10

In [7]:
type(scalar), type(scalar.item())

(torch.Tensor, int)

### Vector

In [8]:
vector = torch.tensor([10, 10])
vector

tensor([10, 10])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

### Matrix

In [11]:
matrix = torch.tensor([
    [10, 7],
    [7, 10]
])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
matrix.ndim

2

### Tensor

In [14]:
tensor = torch.tensor(
    [[[1, 2, 3],
      [4, 5, 6],
      [7, 8, 2]]]
)

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

## Random tensors

In [17]:
random_tensor = torch.rand(size=(244, 244, 3))
random_tensor.ndim, random_tensor.shape

(3, torch.Size([244, 244, 3]))

### zeros tensor


In [18]:
zeros = torch.zeros(size=(4, 4))
zeros, zeros.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([4, 4]))

### ones tensor

In [19]:
ones = torch.ones(size=(4, 4))
ones, ones.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([4, 4]))

### range tensor

In [20]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# will return the same shape as the input tensor

ten_zeros = torch.ones_like(input=zero_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Datatypes

In [22]:
float_32_tensor = torch.tensor([10.0, 7, 10],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float16, device(type='cpu'))

## Matrix multipliciation

In [23]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

tensor_B.ndim, tensor_B, tensor_B.shape

(2,
 tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 torch.Size([3, 2]))

In [24]:
tensor_B.T.ndim, tensor_B.T, tensor_B.T.shape

(2,
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([2, 3]))

## Linear model layer to install the dimensions in ML model

In [43]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2,
                         out_features=3)

print(f"Linear layer: {linear}")

output = linear(tensor_B)

print(f"Input : {tensor_B.shape}")
print(f"Output : {output.shape}")

tensor_B, output

Linear layer: Linear(in_features=2, out_features=3, bias=True)
Input : torch.Size([3, 2])
Output : torch.Size([3, 3])


(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 tensor([[ 9.3091,  5.7512,  0.9657],
         [10.4366,  6.2351,  0.9535],
         [11.5641,  6.7190,  0.9412]], grad_fn=<AddmmBackward0>))

## Finding the min, max, mean, sum, etc (aggregation)

In [48]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [58]:
torch.min(x), torch.max(x), torch.mean(x.type(torch.bfloat16)), torch.sum(x), torch.argmax(x), torch.argmin(x)

(tensor(0),
 tensor(90),
 tensor(45., dtype=torch.bfloat16),
 tensor(450),
 tensor(9),
 tensor(0))

## Reshaping, stacking, squeezing and unsqueezing

In [66]:
tensor = torch.arange(1., 8.)
tensor, tensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [73]:
tensor_reshaped = torch.reshape(tensor, shape=(1, 7))
tensor_reshaped, tensor_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [78]:
tensor_view = tensor.view(1, 7)
tensor_view, tensor_view.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [84]:
tensor[0] = 10
tensor, tensor_view

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.]),
 tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.]]))

In [89]:
tensor_view.squeeze(), tensor_view

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.]),
 tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.]]))

In [91]:
tensor.unsqueeze(1), tensor

(tensor([[10.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.]))