In [109]:
!nvidia-smi

Sun Feb  1 11:51:03 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.80                 Driver Version: 581.80         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060      WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   42C    P3             18W /   78W |    1001MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [252]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [111]:

print(f"torch: {torch.__version__}")
print(f"numpy: {np.__version__}")
print(f"pandas: {pd.__version__}")

torch: 2.7.1+cu118
numpy: 2.3.5
pandas: 3.0.0


## Introduction to tensros

### Creating tensors

### Scalar

In [112]:
# scalar

scalar = torch.tensor(10)
scalar

tensor(10)

In [113]:
scalar.ndim

0

In [114]:
scalar.item()

10

In [115]:
type(scalar), type(scalar.item())

(torch.Tensor, int)

### Vector

In [116]:
vector = torch.tensor([10, 10])
vector

tensor([10, 10])

In [117]:
vector.ndim

1

In [118]:
vector.shape

torch.Size([2])

### Matrix

In [119]:
matrix = torch.tensor([
    [10, 7],
    [7, 10]
])

In [120]:
matrix.shape

torch.Size([2, 2])

In [121]:
matrix.ndim

2

### Tensor

In [122]:
tensor = torch.tensor(
    [[[1, 2, 3],
      [4, 5, 6],
      [7, 8, 2]]]
)

In [123]:
tensor.ndim

3

In [124]:
tensor.shape

torch.Size([1, 3, 3])

## Random tensors

In [125]:
random_tensor = torch.rand(size=(244, 244, 3))
random_tensor.ndim, random_tensor.shape

(3, torch.Size([244, 244, 3]))

### zeros tensor


In [126]:
zeros = torch.zeros(size=(4, 4))
zeros, zeros.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([4, 4]))

### ones tensor

In [127]:
ones = torch.ones(size=(4, 4))
ones, ones.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([4, 4]))

### range tensor

In [128]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
# will return the same shape as the input tensor

ten_zeros = torch.ones_like(input=zero_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor Datatypes

In [130]:
float_32_tensor = torch.tensor([10.0, 7, 10],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float16, device(type='cpu'))

## Matrix multipliciation

In [131]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

tensor_B.ndim, tensor_B, tensor_B.shape

(2,
 tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 torch.Size([3, 2]))

In [132]:
tensor_B.T.ndim, tensor_B.T, tensor_B.T.shape

(2,
 tensor([[ 7.,  8.,  9.],
         [10., 11., 12.]]),
 torch.Size([2, 3]))

## Linear model layer to install the dimensions in ML model

In [133]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2,
                         out_features=3)

print(f"Linear layer: {linear}")

output = linear(tensor_B)

print(f"Input : {tensor_B.shape}")
print(f"Output : {output.shape}")

tensor_B, output

Linear layer: Linear(in_features=2, out_features=3, bias=True)
Input : torch.Size([3, 2])
Output : torch.Size([3, 3])


(tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]),
 tensor([[ 9.3091,  5.7512,  0.9657],
         [10.4366,  6.2351,  0.9535],
         [11.5641,  6.7190,  0.9412]], grad_fn=<AddmmBackward0>))

## Finding the min, max, mean, sum, etc (aggregation)

In [134]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [135]:
torch.min(x), torch.max(x), torch.mean(x.type(torch.bfloat16)), torch.sum(x), torch.argmax(x), torch.argmin(x)

(tensor(0),
 tensor(90),
 tensor(45., dtype=torch.bfloat16),
 tensor(450),
 tensor(9),
 tensor(0))

## Reshaping, stacking, squeezing and unsqueezing

In [136]:
tensor = torch.arange(1., 8.)
tensor, tensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [137]:
tensor_reshaped = torch.reshape(tensor, shape=(1, 7))
tensor_reshaped, tensor_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [138]:
tensor_view = tensor.view(1, 7)
tensor_view, tensor_view.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [139]:
tensor[0] = 10
tensor, tensor_view

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.]),
 tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.]]))

In [140]:
tensor_view.squeeze(), tensor_view

(tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.]),
 tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.]]))

In [141]:
tensor.unsqueeze(dim=0), tensor

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.]))

In [142]:
# permute

x = torch.rand(size=(255, 255, 3))
permuted_x = x.permute(2, 0, 1)

x.shape, permuted_x.shape

(torch.Size([255, 255, 3]), torch.Size([3, 255, 255]))

## Indexing

In [150]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [154]:
# index by bracket

print(f"First bracket \n{x[0]}")
print(f"Second bracket \n{x[0][0]}")
print(f"Third bracket \n{x[0][0][0]}")

First bracket 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second bracket 
tensor([1, 2, 3])
Third bracket 
1


In [171]:
x = torch.arange(1, 10).reshape(3, 3)
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [186]:
x[0:3:2, ::2]

tensor([[1, 3],
        [7, 9]])

In [188]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [213]:
# (rows, columns)

x[:, :, 0]

tensor([[1, 4, 7]])

In [221]:
array = np.arange(1., 10.)
tensor = torch.arange(1., 10.)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [229]:
# tensor to array and array to rensor

tensor.numpy().dtype, torch.from_numpy(array).type(dtype=torch.float32).dtype

(dtype('float32'), torch.float32)

# Reproducibility (trying to take the random out of random)

In [230]:
# create two random numbers without manual seed

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.2282, 0.5114, 0.7474, 0.3652],
         [0.4725, 0.5773, 0.0517, 0.5271],
         [0.5473, 0.0855, 0.0078, 0.4795]]),
 tensor([[0.8685, 0.1379, 0.9014, 0.6396],
         [0.7451, 0.2902, 0.4987, 0.0369],
         [0.5494, 0.4745, 0.6425, 0.4817]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [234]:
# create two random numbers with manual_seed 42

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.random.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)


random_tensor_C, random_tensor_D, random_tensor_C == random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

# PyTorch to run on the GPU

In [239]:
# if true than you are good to go

torch.cuda.is_available()

True

In [ ]:
# device agnostic code

device = "cuda" if torch.cuda.is_available() else "CPU"

'cuda'

In [243]:
# number of GPUs PyTorch is using

torch.cuda.device_count()

1

In [255]:
tensor = torch.arange(0., 101., 5)
tensor, tensor.device

(tensor([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
          60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.]),
 device(type='cpu'))

In [256]:
tensor_to_gpu = tensor.to(device)
tensor_to_gpu, tensor_to_gpu.device

(tensor([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,
          60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.], device='cuda:0'),
 device(type='cuda', index=0))

In [258]:
# now convert the gpu tensor back to cpu if you wanna use it with nummPy, cuz numPy dont leverage the gpu

tensor_back_on_cpu = tensor_to_gpu.cpu().numpy()
tensor_back_on_cpu

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.],
      dtype=float32)

> # Exercise

In [259]:
# Create a random tensor with shape (7, 7)

random_tensor = torch.rand(size=(7, 7))
random_tensor.shape

torch.Size([7, 7])

In [268]:
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
# (hint: you may have to transpose the second tensor)

tensor_B = torch.arange(1, 8).reshape(1, 7)

random_tensor, tensor_B.T, random_tensor @ tensor_B.T.type(torch.float32)

(tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7]]),
 tensor([[15.6824],
         [10.3553],
         [13.8352],
         [16.2412],
         [18.4342],
         [11.3081],
         [15.0432]]))

In [270]:
# Set the random seed to 0 and do exercises 2 & 3 over again.

torch.manual_seed(0)

# Create a random tensor with shape (7, 7)

random_tensor = torch.rand(size=(7, 7))
print(f"random tensor [7, 7]: {random_tensor.shape}")

# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)
# (hint: you may have to transpose the second tensor)

tensor_B = torch.arange(1, 8).reshape(1, 7)

random_tensor, tensor_B.T, random_tensor @ tensor_B.T.type(torch.float32)

random tensor [7, 7]: torch.Size([7, 7])


(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7]]),
 tensor([[11.5985],
         [ 8.4247],
         [13.8940],
         [14.7436],
         [ 9.1287],
         [14.7049],
         [12.8201]]))

In [272]:
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
# (hint: you'll need to look into the documentation for torch.cuda for this one).
# If there is, set the GPU random seed to 1234

torch.cuda.manual_seed(1234)

In [277]:
# Create two random tensors of shape (2, 3) and 
# send them both to the GPU (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors(this doesn't have to be the GPU random seed

torch.manual_seed(1234)

tensor_A = torch.rand(size=(2, 3))
tensor_B = torch.rand(size=(2, 3))

tensor_A_on_gpu = tensor_A.to(device)
tensor_B_on_gpu = tensor_B.to(device)

tensor_A_on_gpu, tensor_B_on_gpu

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [285]:
# Perform a matrix multiplication on the tensors you created in 6 
# (again, you may have to adjust the shapes of one of the tensors).

tensor_C = tensor_A_on_gpu @ tensor_B_on_gpu.T
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [287]:
# Find the maximum and minimum values of the output of 7.

tensor_C.max(), tensor_C.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [288]:
# Find the maximum and minimum index values of the output of 7.

torch.argmax(tensor_C), torch.argmin(tensor_C)

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [291]:
# Make a random tensor with shape (1, 1, 1, 10) and 
# then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and 
# it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)

tensor_D = torch.rand(size=(1, 1, 1, 10))
print(f"Tensor : {tensor_D}, with shape {tensor_D.shape}")

tensor_D_squeezed = tensor_D.squeeze()
print(f"Tensor : {tensor_D_squeezed}, with shape {tensor_D_squeezed.shape}")


Tensor : tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), with shape torch.Size([1, 1, 1, 10])
Tensor : tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), with shape torch.Size([10])
