In [1]:
!nvidia-smi

Fri Jan 30 17:35:00 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 581.80                 Driver Version: 581.80         CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060      WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   56C    P0             24W /   78W |    1268MiB /   6144MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:

print(f"torch: {torch.__version__}")
print(f"numpy: {np.__version__}")
print(f"pandas: {pd.__version__}")

torch: 2.7.1+cu118
numpy: 2.3.5
pandas: 3.0.0


## Introduction to tensros

### Creating tensors

### Scalar

In [4]:
# scalar

scalar = torch.tensor(10)
scalar

tensor(10)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

10

In [7]:
type(scalar), type(scalar.item())

(torch.Tensor, int)

### Vector

In [8]:
vector = torch.tensor([10, 10])
vector

tensor([10, 10])

In [9]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

### Matrix

In [16]:
matrix = torch.tensor([
    [10, 7],
    [7, 10]
])

In [18]:
matrix.shape

torch.Size([2, 2])

In [19]:
matrix.ndim

2

### Tensor

In [24]:
tensor = torch.tensor(
    [[[1, 2, 3],
      [4, 5, 6],
      [7, 8, 2]]]
)

In [25]:
tensor.ndim

3

In [27]:
tensor.shape

torch.Size([1, 3, 3])

## Random tensors

In [32]:
random_tensor = torch.rand(size=(244, 244, 3))
random_tensor.ndim, random_tensor.shape

(3, torch.Size([244, 244, 3]))

### zeros tensor


In [34]:
zeros = torch.zeros(size=(4, 4))
zeros, zeros.shape

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.Size([4, 4]))

### ones tensor

In [36]:
ones = torch.ones(size=(4, 4))
ones, ones.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([4, 4]))

### range tensor

In [46]:
zero_to_ten = torch.arange(0, 10, 1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# will return the same shape as the input tensor

ten_zeros = torch.ones_like(input=zero_to_ten)
ten_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

: 

## Tensor Datatypes