In [2]:
import tensorflow as tf

In [ ]:
tf.__version__

In [ ]:
print(tf.__version__)

# Creating Tensors with tf.constant

In [ ]:
scalar = tf.constant(1)

scalar

#### Check the numbers of dimensions of tensors using function ndim(stands for number of dimensions)

In [11]:
scalar.ndim

0

In [18]:
# Vectors have one dimensions

vector = tf.constant([1, 2, 3])

vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [20]:
# Check the dimension of the vector

vector.ndim

1

In [21]:
# Create a matrix more than 1 dimension

matrix = tf.constant([[1, 2], [3, 4]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [22]:
# check the dimensions of the matrix

matrix.ndim

2

In [11]:
another_matrix = tf.constant([
    [2., 5.],
    [6., 9.]
], dtype = 'float16')

another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[2., 5.],
       [6., 9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

# Creating Tensors With tf.variable

In [ ]:
changable_tensors = tf.Variable([5, 10])

changable_tensors

#### To change Tensors value assign() functions is used

In [22]:
changable_tensors[0].assign(1)

changable_tensors

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 1, 10])>